language: php
php:
  - 5.6
  - 7
sudo: false
branches:
  only:
    - master
    - develop
env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=inc@2inc.org
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=inc@2inc.org
    - secure: "t7yhRcGV3ob/NYng7+cXqrPOPjrbLwPasoRmXbSXINrawljZ8BwBdlRCwTLxMybMBk6MTgTq2FdQxIvCB/axB1NyQyQ4MIAuaNFd1iqZTPs1ptxne8Ur90ZV77tNQIJ1zYsmm4LHbrc9vFZ8eM4k8NZy4FOomOSMcPEQwBOyA5EpP7zWTlzjLMdX3dGc3F3h7UzhdfZZH8x34SQtUCu9L5C9V1JwGTJA3nS/Wnd/krH4gQPKKebh98PMfh7Kf2FOA4aJjOaTJ8NHWtwoB4CJBbKtKt7YEHGCb6j5yK5cMy+8ymb74Mtya5z0APBmmkUib23m455Nm0GgwVenwKYpC/Fr3L+pc4eJ9I+wDlpM7P1y3h8RxSMPS9UawhO0StAxkDYg96tEgqEWfGNsb39b0rjtWYfZtFAnMTAYZL9G7C0RA72dMObuipJlyiFtsokYYes81hgrlXx1fcc5IUKPUr7yCeNXbasaPLXubzyZ/73QQMOc2akKCGo6I7DXOBpz8nFJvYe/MolTYkCWbGxULJ85nNkaQdYN7qXZQAIa6edtnNliwjJP22wKn1GMbFzFvOWwO5OK19XBLX7BpbE0sXw9RWn++X1xR1Ipq6RAQlI5KIhSNXo9xwg3yygz2zr4LPw/aObUQEgOLQRvEqBNwfqOl2h7VAegzQLSO6sV/7o="
cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache
install:
  - composer install
  - nvm install 6
  - npm install
script:
  - npm run gulp build
  - ls -la style.css
  - composer test
before_deploy:
  - git clone -b wprepository --quiet https://github.com/inc2734/mimizuku.git wprepository
  - cd wprepository
  - ls | xargs rm -rf
  - rsync -a ../ ./ --exclude "/wprepository/" --exclude "/node_modules/" --exclude "/vendor/"
  - rm -rf bin codesniffer.ruleset.xml node_modules gulpfile.js package.json phpmd.ruleset.xml
  - rm -rf .gitignore .travis.yml .DS_Store
  - ls -la
  - cd ../
deploy:
  provider: script
  script: bash ./bin/wprepository.sh
  skip_cleanup: true
  on:
    branch: master
    php: 7
